### ISSUE TITLE
This repository label is out of the search box

### ISSUE THREAD

**Issue by sergatgh** [DVDAndroid/GitHubMaterialDesign#1]
Hi @DVDAndroid ,

I think  "This repository" label is not on its place:

![image](https://cloud.githubusercontent.com/assets/5488829/17271312/8e36f36a-5680-11e6-9d06-44b41338575f.png)

I'm using Google Chrome Version 52.0.2743.82 (64-bit) on linux

**Comment by sergatgh** [comment]
I'm not an experienced front-end developer, but hiding lines:

/* .header-search-wrapper {
    display: inline;
} */

works for me.

**Comment by DVDAndroid** [comment]
Yeah, that is the fix
