### ISSUE TITLE
Text in search input is in front of the icon

### ISSUE THREAD

**Issue by sergatgh** [DVDAndroid/GitHubMaterialDesign#2]
Hi @DVDAndroid ,

When I use Issues tab of the repository there is a text in the filter text box. This text appears to be not on its own place:

![image](https://cloud.githubusercontent.com/assets/5488829/18224256/33cff11a-71d8-11e6-9c96-bdb799f6cf96.png)

In the original design there is a left-padding of 30px:

![image](https://cloud.githubusercontent.com/assets/5488829/18224280/b935b01a-71d8-11e6-8d73-00b1d7dc8c28.png)

Which seem to be overridden by material design:

![image](https://cloud.githubusercontent.com/assets/5488829/18224294/24e7d950-71d9-11e6-84a3-37633edcc4b6.png)

**Comment by DVDAndroid** [comment]
Thanks for reporting bugs; update pushed
