### ISSUE TITLE
Dark Version ?

### ISSUE THREAD

**Issue by TheSpartaPT** [DVDAndroid/GitHubMaterialDesign#3]
it is too bright can't you make a dark version ? if not i'll just edit your's when i find some spare time ...

everything else looks good, great job!

**Comment by DVDAndroid** [comment]
No, sorry

**Comment by DVDAndroid** [comment]
You can use [https://github.com/StylishThemes/GitHub-Dark](https://github.com/StylishThemes/GitHub-Dark)
