### ISSUE TITLE
search text color

### ISSUE THREAD

**Issue by TheSpartaPT** [DVDAndroid/GitHubMaterialDesign#4]
the text color is white and the text box is also white so you can't see what you're typing,
add this:
.header-search-input {
    color: black !important;
}

Before:

![before1](https://cloud.githubusercontent.com/assets/8343238/23373306/53ae5006-fd17-11e6-9306-2cc943a49082.png)

![before2](https://cloud.githubusercontent.com/assets/8343238/23373307/53b2a2e6-fd17-11e6-8a2b-f55b9f7d04da.png)

After:

![result](https://cloud.githubusercontent.com/assets/8343238/23373219/de661f7c-fd16-11e6-9d9b-cf3a129d5fe1.png)

**Comment by DVDAndroid** [comment]
Thanks for bug reporting. I was unable to reproduce it because I had installed a Chrome extension for Github and it caused a conflict of themes.
