### ISSUE TITLE
Casella di testo ridotta | Textarea collapsed

### ISSUE THREAD

**Issue by maicol07** [DVDAndroid/GitHubMaterialDesign#5]
Ciao,

Il tema è il migliore material design tra quelli esistenti su Stylish ma potresti risolvere il bug della casella di testo nella modifica/creazione di un file?

Grazie

Guarda qui il problema: [link](https://forum.userstyles.org/discussion/50871/code-editor-is-collapsed)

-------

**ENGLISH** 

Hi,
The theme is the best material design in the Stylish website but could you fix the bug of the textures while creating/editing files/gists?

Thanks

See here the issue: [link](https://forum.userstyles.org/discussion/50871/code-editor-is-collapsed)

_Sent from my ZenFone 3 (ZE520KL) using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by maicol07** [comment]
Quindi?

-----------

**EN**
So?

**Comment by DVDAndroid** [comment]
I'll fix it when I'll get free time

**Comment by maicol07** [comment]
Any news?

**Comment by maicol07** [comment]
? I can't use the theme with this bug...

**Comment by DVDAndroid** [comment]
@maicol07 mi sto uccidendo per la maturità fai te

**Comment by maicol07** [comment]
Scusa, non lo sapevo... se mi dici dove devo controllare per risolvere posso provarci...

**Comment by DVDAndroid** [comment]
Nessun problema ☺️
Stasera vedo di trovare qualche minuto
Il file è un po' vecchiotto, sinceramente non mi ricordo la classe o il tag css da modificare

**Comment by maicol07** [comment]
![immagine](https://user-images.githubusercontent.com/9463142/37220850-28ccb46c-23c8-11e8-8ab1-f7cf28a3630b.png)
Questo può esserti d'aiuto?

**Comment by maicol07** [comment]
Grazie mille! Funziona!
